### ISSUE TITLE
`latest` tag missing

### ISSUE THREAD

**Issue by GeoffreyBooth** [dollarshaveclub/vault-dev-docker#5]
It appears that this can only be pulled via `quay.io/dollarshaveclub/vault-dev:master`. It would be nice if a `latest` tag were pushed as well, so that people could pull this via just `quay.io/dollarshaveclub/vault-dev`.

**Comment by bkeroackdsc** [comment]
Oops! Thanks for pointing out the oversight. I just pushed the `latest` tag.
